name: "🐛 Bug Report"
description: Report a bug or unexpected behavior
title: "fix: "
labels: ["fix"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this bug. Please provide details to help us investigate and resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Clearly describe what the bug is and how it manifests."
      placeholder: "e.g., Build fails with TypeScript error when running pnpm build."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the bug."
      placeholder: |
        1. Copy template from ts/with-turborepo
        2. Run `pnpm install`
        3. Run `pnpm build`
        4. Observe the error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "Describe what should happen."
      placeholder: "e.g., Build should complete without errors."
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually occurs."
      placeholder: "e.g., Build fails with 'Type not found' error."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Provide relevant system and tool versions."
      placeholder: |
        - OS: Ubuntu 24.04
        - Node: 20.11.0
        - pnpm: 8.15.6
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Error Logs"
      description: "Paste any error messages or terminal output."
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Include any references, links, or other relevant information."
      placeholder: "e.g., Related issue, similar behavior, workaround."
    validations:
      required: false
