name: "🐛 Bug Report"
description: Report a bug or unexpected behavior
title: "fix: "
labels: ["fix"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this bug. Please provide details to help us investigate and resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a concise summary of the bug, any visible symptoms, and where it appears."
      placeholder: "e.g., Running `pnpm build` in ts/with-turborepo exits with a TypeScript error before assets compile."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "List the minimum actions needed to trigger the bug."
      placeholder: |
        1. Copy template from ts/with-turborepo
        2. Run `pnpm install`
        3. Run `pnpm build`
        4. Observe the error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "State the outcome you anticipated after following the reproduction steps."
      placeholder: "e.g., Build completes successfully and outputs production bundles without warnings."
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "Explain what happened instead. Include screenshots or terminal snippets if helpful."
      placeholder: "e.g., Build aborts at 35% with `TS2307: Cannot find module '@/components/button'`."
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "List versions and configuration details that might influence the bug."
      placeholder: |
        - OS: Ubuntu 24.04
        - Node: 20.11.0
        - pnpm: 8.15.6
        - Template: ts/with-turborepo (commit abc123)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Error Logs"
      description: "Paste relevant log excerpts, stack traces, or command output. Use fenced blocks for clarity."
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add links to related issues, PRs, or temporary workarounds."
      placeholder: "e.g., Related issue #123, temporary workaround is to pin @repo/ui to 0.1.4."
    validations:
      required: false
