name: "🚀 Feature Request"
description: Suggest a new feature or improvement
title: "feat: "
labels: ["feat"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Clearly describe the feature or improvement you'd like to see."
      placeholder: "e.g., Add dark mode support to the dashboard."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation / Use Case"
      description: "Explain why this feature is needed or what problem it solves."
      placeholder: "e.g., Dark mode would improve usability at night."
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Tasks / To-Do List"
      description: "Outline the steps or tasks required to implement this feature."
      placeholder: |
        - [ ] Add toggle in settings
        - [ ] Implement dark theme CSS
        - [ ] Save theme preference in user profile
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Include any alternatives considered, related issues, screenshots, or references."
      placeholder: "e.g., Similar implementation in another app, or links to related issues."
    validations:
      required: false
